export default {
  login: 'Vladyslav8919',
  id: 117685818,
  node_id: 'U_kgDOBwO-Og',
  avatar_url: 'https://avatars.githubusercontent.com/u/117685818?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/Vladyslav8919',
  html_url: 'https://github.com/Vladyslav8919',
  followers_url: 'https://api.github.com/users/Vladyslav8919/followers',
  following_url:
    'https://api.github.com/users/Vladyslav8919/following{/other_user}',
  gists_url: 'https://api.github.com/users/Vladyslav8919/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/Vladyslav8919/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/Vladyslav8919/subscriptions',
  organizations_url: 'https://api.github.com/users/Vladyslav8919/orgs',
  repos_url: 'https://api.github.com/users/Vladyslav8919/repos',
  events_url: 'https://api.github.com/users/Vladyslav8919/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/Vladyslav8919/received_events',
  type: 'User',
  site_admin: false,
  name: 'Vladyslav Pshevlotskyi',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 54,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2022-11-07T20:48:33Z',
  updated_at: '2023-01-16T09:12:57Z',
};
